exclude: |
  (?x)(
    ^docs/conf.py|
    ^docs/license.rst
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=50000"]
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=auto"]
      # - id: pretty-format-json
      #   args: ["--autofix", "--no-sort-keys", "--no-ensure-ascii"]
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [css, yaml, markdown, html, scss, javascript, json]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --output-format=full]
      # Run the formatter
      - id: ruff-format
