[tox]
env_list =
    python
    precommit
    mypy
recreate = True

[testenv]
base_python = python
dependency_groups = dev

[testenv:python]
commands = pytest --cov=. --cov-report= --cov-append -s -m 'not integration'

[testenv:precommit]
commands = pre-commit run --all-files

[testenv:mypy]
commands = mypy --show-error-codes pyseed
